name: deploy nexturl to vercel
on:
  push:
    branches:
      - main

jobs:
  vercel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy site to Vercel
        run: npx vercel --prod -t ${{ secrets.VERCEL_TOKEN }} --confirm
