name: Deploy to Vercel
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    # this will deploy data files only when no release is created
    branches:
      - main
    paths:
      - "data/**"

jobs:
  build:
    runs-on : ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use NodeJs 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: npm -ci
      - run: npm run build --if-present
      - run: npm run test --if-present
  
  deploy:
    if: github.repository == 'Project-Eco-Track/Eco-Track'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install Vercel CLI
        run: npm install --global vercel@latest
      - name: pull Vercel environment information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: build project artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: deploy project artifacts to Vercel
        run: |
          du --inodes -d 5 .vercel/output
          vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
